"""autogenerated by genmsg_py from SegStatus.msg. Do not edit."""
import roslib.message
import struct


class SegStatus(roslib.message.Message):
  _md5sum = "e477a5a36954f5c7c17a1e9ccc85a7c9"
  _type = "alpha_steering/SegStatus"
  _has_header = False #flag to mark the presence of a Header object
  _full_text = """bool segComplete

uint64 seg_number

float64 progress_made
"""
  __slots__ = ['segComplete','seg_number','progress_made']
  _slot_types = ['bool','uint64','float64']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.
    
    The available fields are:
       segComplete,seg_number,progress_made
    
    @param args: complete set of field values, in .msg order
    @param kwds: use keyword arguments corresponding to message field names
    to set specific fields. 
    """
    if args or kwds:
      super(SegStatus, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.segComplete is None:
        self.segComplete = False
      if self.seg_number is None:
        self.seg_number = 0
      if self.progress_made is None:
        self.progress_made = 0.
    else:
      self.segComplete = False
      self.seg_number = 0
      self.progress_made = 0.

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    @param buff: buffer
    @type  buff: StringIO
    """
    try:
      _x = self
      buff.write(_struct_BQd.pack(_x.segComplete, _x.seg_number, _x.progress_made))
    except struct.error as se: self._check_types(se)
    except TypeError as te: self._check_types(te)

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    @param str: byte array of serialized message
    @type  str: str
    """
    try:
      end = 0
      _x = self
      start = end
      end += 17
      (_x.segComplete, _x.seg_number, _x.progress_made,) = _struct_BQd.unpack(str[start:end])
      self.segComplete = bool(self.segComplete)
      return self
    except struct.error as e:
      raise roslib.message.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    @param buff: buffer
    @type  buff: StringIO
    @param numpy: numpy python module
    @type  numpy module
    """
    try:
      _x = self
      buff.write(_struct_BQd.pack(_x.segComplete, _x.seg_number, _x.progress_made))
    except struct.error as se: self._check_types(se)
    except TypeError as te: self._check_types(te)

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    @param str: byte array of serialized message
    @type  str: str
    @param numpy: numpy python module
    @type  numpy: module
    """
    try:
      end = 0
      _x = self
      start = end
      end += 17
      (_x.segComplete, _x.seg_number, _x.progress_made,) = _struct_BQd.unpack(str[start:end])
      self.segComplete = bool(self.segComplete)
      return self
    except struct.error as e:
      raise roslib.message.DeserializationError(e) #most likely buffer underfill

_struct_I = roslib.message.struct_I
_struct_BQd = struct.Struct("<BQd")
