"""autogenerated by genmsg_py from MagEngaged.msg. Do not edit."""
import roslib.message
import struct


class MagEngaged(roslib.message.Message):
  _md5sum = "cd9f332ec2c157f407b1400742281d53"
  _type = "msg_alpha/MagEngaged"
  _has_header = False #flag to mark the presence of a Header object
  _full_text = """#Will be message determining if the magnet should be enabled or not

bool mag_engaged
"""
  __slots__ = ['mag_engaged']
  _slot_types = ['bool']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.
    
    The available fields are:
       mag_engaged
    
    @param args: complete set of field values, in .msg order
    @param kwds: use keyword arguments corresponding to message field names
    to set specific fields. 
    """
    if args or kwds:
      super(MagEngaged, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.mag_engaged is None:
        self.mag_engaged = False
    else:
      self.mag_engaged = False

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    @param buff: buffer
    @type  buff: StringIO
    """
    try:
      buff.write(_struct_B.pack(self.mag_engaged))
    except struct.error as se: self._check_types(se)
    except TypeError as te: self._check_types(te)

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    @param str: byte array of serialized message
    @type  str: str
    """
    try:
      end = 0
      start = end
      end += 1
      (self.mag_engaged,) = _struct_B.unpack(str[start:end])
      self.mag_engaged = bool(self.mag_engaged)
      return self
    except struct.error as e:
      raise roslib.message.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    @param buff: buffer
    @type  buff: StringIO
    @param numpy: numpy python module
    @type  numpy module
    """
    try:
      buff.write(_struct_B.pack(self.mag_engaged))
    except struct.error as se: self._check_types(se)
    except TypeError as te: self._check_types(te)

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    @param str: byte array of serialized message
    @type  str: str
    @param numpy: numpy python module
    @type  numpy: module
    """
    try:
      end = 0
      start = end
      end += 1
      (self.mag_engaged,) = _struct_B.unpack(str[start:end])
      self.mag_engaged = bool(self.mag_engaged)
      return self
    except struct.error as e:
      raise roslib.message.DeserializationError(e) #most likely buffer underfill

_struct_I = roslib.message.struct_I
_struct_B = struct.Struct("<B")
